### ISSUE TITLE
Grid example with ag-Grid column filters

### ISSUE THREAD

**Issue by amcclain** [xh/toolbox#128]
While proper support for ag-Grid provided column filters is still a pending item, we have enough real-world usages of these filters via the AG API that we need to be able to test and experiment with them in Toolbox.

We should add this as a dedicated grid in its own tab - i.e. specifically *don't* want to add them to the standard grid that's reused across examples as we can't fully recommend their use at this point.

**Comment by shravnk** [comment]
See #139

**Comment by lbwexler** [comment]
Closing this.  First class Hoist column filters will be included in v42.
