### ISSUE TITLE
Reduce load on NewsFeed

### ISSUE THREAD

**Issue by lbwexler** [xh/toolbox#228]
Our news feed is currently getting 429 errors (Too Many Requests).

Might be related to increasing toolbox development, stops/starts etc.

Might be enough to just set the default refresh time to -1 to quiet development machines and allow our server instances to make all requests.

We could also consider making the cache lazy, and simply time out old results.  This would probably be the best solution.

**Comment by peterjcoffman** [comment]
Pull request is here:
https://github.com/xh/toolbox/pull/292

**Comment by lbwexler** [comment]
Fixed!  Using a more efficient API, and more importantly, creating the timer that runs the whole show lazily, so that development servers will never ping API unless needed. 👍
