### ISSUE TITLE
Status monitors for new Grails services

### ISSUE THREAD

**Issue by amcclain** [xh/toolbox#244]
Now that we have some nice server-side services, we can write some meaningful status monitors within `MonitorDefinitionService` and provide a much better demo of that feature.

**Comment by peterjcoffman** [comment]
There are a few things in the existing monitors that need to be changed. Most notably, we get NullPointerExceptions if the news has never been fetched. Also, the threshold on Loaded Stories is incorrect. It's set to zero, which means it will only fail if there are fewer than zero stories (clearly impossible). I'll fix those things while I'm adding more monitors.

I also think there's a shortcoming in the way the MonitorService currently works. Let's say you want the monitor to fail if the most recent news story was over 360 minutes ago, like it works now. If the last news story does not exist, i.e. the news has NEVER been fetched, there is no sensible way to handle that. I think the way to do it would be to "abort" using the numeric metric and instead just print a message and manually set it to fail.

We could do that by, say, having MonitorResultService.evaluateThresholds do nothing at all if the resultStatus is already set.

**Comment by peterjcoffman** [comment]
I don't think that change is important. We can come pretty close to the behavior I want within the current API.
