### ISSUE TITLE
Portfolio example - configure multi-level tree as default

### ISSUE THREAD

**Issue by amcclain** [xh/toolbox#247]
Currently I _believe_ the dimension chooser is unconfigured, causing it to default to a one-level "tree" with the first dimension in the list (Fund) - which happens to be the most boring grouping you could show out of the box in terms of row count and failing to show off the entire tree idea.

Suggest Sector > Symbol as a better default grouping. We could also look at configuring the grid to expand all those nodes by default.

Note that I do *not* think we should wire up a preference here to remember the last grouping, as multiple random users might change and leave it on a setting we don't care to show off - we want to control that default / first look at the example for new viewers.

As part of this, would like to pre-config a few other useful groupings in the dimension chooser's history list.  I think that is possible.

**Comment by peterjcoffman** [comment]
There is currently a preference to remember previous groupings. However, it is a local preference so it will not affect other users.

**Comment by peterjcoffman** [comment]
Pull request is here:
https://github.com/xh/toolbox/pull/288
