### ISSUE TITLE
Give toolbox example apps their own titles in page header

### ISSUE THREAD

**Issue by inewell** [xh/toolbox#252]
All the apps, (portfolio, recalls, etc.) are titled "Toolbox (Development)". In hoist-react/static/index.html, the title is given by `htmlWebpackPlugin.options.title`. Because the example apps are still part of the Toolbox app and not fully standalone, they don't get their own titles.

**Comment by lbwexler** [comment]
This is getting fixed in HoistReact https://github.com/xh/hoist-react/pull/1666
