### ISSUE TITLE
Update "Factories vs JSX" wrapper intro text

### ISSUE THREAD

**Issue by amcclain** [xh/toolbox#264]
Could use a light update re. the new variants off of `hoistComponent` vs call out to `elemFactory`

**Comment by lbwexler** [comment]
Happy to help with this -- could be a good learning opportunity. There may also be some text in the readme that should be updated.

**Comment by petradish** [comment]
Will take a stab at it!

**Comment by lbwexler** [comment]
This is part of a general need for documentation update -- not worth calling out this ticket
