### ISSUE TITLE
Toolbox-> Grids-> Standard -> Export to Excel : No Grouping  

### ISSUE THREAD

**Issue by mpeckerman** [xh/toolbox#268]
1. Navigate to Toolbox-> Grid Tab-> Standard subtab
2. Select 'Group by' option 
3. Click on 'Export' icon
4. Wait for 'Export Complete' message
5. Review file -> Rows are displayed in 'flat' format (note attached)  
[hoist-sample-export (1).xlsx](https://github.com/xh/toolbox/files/3643659/hoist-sample-export.1.xlsx)

**Comment by lbwexler** [comment]
Would it be possible for them to export with the native Excel Tree format?

**Comment by lbwexler** [comment]
I'll open in Hoist React for consideration -- not a toolbox issue.
