### ISSUE TITLE
Remove JSX in Portfolio example

### ISSUE THREAD

**Issue by peterjcoffman** [xh/toolbox#290]
The Portfolio example has JSX versions of all components maintained in parallel with the XH-preferred factories. These two versions are difficult to keep in sync, so the JSX model should be removed before we work on further improving the Portfolio example.

**Comment by peterjcoffman** [comment]
Pull request is here:

https://github.com/xh/toolbox/pull/291

**Comment by lbwexler** [comment]
🌮
