### ISSUE TITLE
Add Hoist RoadMap

### ISSUE THREAD

**Issue by lbwexler** [xh/toolbox#302]
Might be nice to have the Hoist RoadMap in toolbox.   Client asked for our published road map the other day.

Could eventually be a data driven listing, that admins could edit in the admin area -- might be a nice starter project for a joiner.  Would also be happy for it to start as just static page

**Comment by amcclain** [comment]
I think this should either be a nice data-driven example with an admin editor, or it should be a comp that reads and formats a (to-be-added) ROADMAP.md file in the hoist-react repo.

The advantages of the markdown file as I see them would be that we could see the diffs over time and it would be a close analog to CHANGELOG.md right within the project.

The advantages of the data-driven Toolbox approach is that it would be a fun example and give us a bit more flexibility with how we define our roadmap.  And maybe seeing how we need to adjust it over time wouldn't _always_ be the best idea 😉 

One other option might be some kind of other GH integration - i.e. if we can use their API to query issues with a tag or milestones or something.

Happy to discuss - let's come up with a plan.

**Comment by lbwexler** [comment]
If it also will include hoist-core work, could imagine it being an advantage having it not live in hoist-react (could still be in git).  

So there is the question as to whether we want a single hoist "roadmap"

**Comment by lbwexler** [comment]
Unable to add a new phase to an empty roadmap.  Let's troubleshoot tommorrow AM so we can get this in.

**Comment by petradish** [comment]
Fixed bugs!
