### ISSUE TITLE
Add Dialog example

### ISSUE THREAD

**Issue by amcclain** [xh/toolbox#307]
We have the Other > Popups example tab for alerts, confirms, etc. but we don't have a tab for core custom dialogs. I believe that part of the issue here is that we want to fully Hoist-ify (or replace) the BP component, but I think dialogs are core enough that we should add an example sooner vs. later.

**Comment by lbwexler** [comment]
Closing this Ticket -- This will certainly be extensively addressed with example powering the new Dialogs which is at this point pretty close.
