### ISSUE TITLE
Improve "gridStyleSwitches" helper component

### ISSUE THREAD

**Issue by amcclain** [xh/toolbox#315]
We currently have a `gridStyleSwitches` component that uses an `AgGridModel` and is applied across several sample grids, including the `AgGridWrapper` example. We want to be able to cleanly add some options to the `Grid` examples that expose controls on the `GridModel` API as well, so we need to reorganize a bit.

I propose we:
* Create a new directory `/src/desktop/common/grid` to hold all the common grid stuff.
* Create an `options` sub-directory off of that for the comps described below.
* Create an `agGridOptions` comp that uses `AgGridModel` and renders the existing switches in an outer vframe.
* Create a `gridOptions` comp that uses `GridModel` and includes an `agGridOptions` comp as its first child (passing it the `agGridmodel`). It can then include any additional inputs to control Grid-specific features.
* Create two wrapper components `agGridOptionsPanel` and `gridOptionsPanel` that each include their core options and add the same panel wrapper with the CSS class and sizing defaults.
* Use those new wrapper components in all the example grids where we currently have the options panel.

Hopefully that sounds like a workable plan to break things up while still getting a nice amount of standardization and re-use.

**Comment by amcclain** [comment]
(Might make more sense to render the raw options components in a fragment vs. a vframe - give it a try and see what works best and is easiest to reuse)

**Comment by peterjcoffman** [comment]
WIP PR:
https://github.com/xh/toolbox/compare/gridOptionsPanel?expand=1
