### ISSUE TITLE
Sync status monitors between dev <> prod

### ISSUE THREAD

**Issue by amcclain** [xh/toolbox#318]
Looks like we need to enter in the latest status monitor definitions in the "prod" toolbox.xh.io instance.

**Comment by peterjcoffman** [comment]
We need to restart the monitorDefinitionService, I believe. I can enter the definitions in the 'config' page, but the corresponding monitors are not created.

I do not know how to re-run the monitorDefinitionService.

**Comment by amcclain** [comment]
Hi - as discussed, we checked and see that the deployed production version of Toolbox does not include the missing monitors I was seeing in dev.  Apologies I did not realize in advance that those were added since the last versioned release.

But thank you for adding them as "inactive" on the production site, so we can then turn them on and verify as soon as we do our next release. 👍

**Comment by peterjcoffman** [comment]
Finished adding the configs.
