### ISSUE TITLE
Portfolio - better default zoom for price charts

### ISSUE THREAD

**Issue by amcclain** [xh/toolbox#322]
Now that we have merged https://github.com/xh/hoist-react/pull/1505 I suggest we improve the portfolio example price charts by:

+ Setting a default zoom of three months or similar.  This makes it more clear what the navigator component is for, in case someone has not seen that before.
+ Enable range buttons for preset zoom values.

**Comment by peterjcoffman** [comment]
PR:
https://github.com/xh/toolbox/pull/324
