### ISSUE TITLE
The News Feed links don't redirect / navigate to the selected news article / story window

### ISSUE THREAD

**Issue by mpeckerman** [xh/toolbox#329]
1. Navigate to Toolbox -> Examples
2. Click News -> Launch App 
3. Navigate to News screen
4. Select a News Feed and click on a link 
The application doesn't redirect to the selected news story

**Comment by peterjcoffman** [comment]
I believe the Record API recently changed and broke the News feed.

PR:
https://github.com/xh/toolbox/pull/334

**Comment by lbwexler** [comment]
👍
