### ISSUE TITLE
Recalls incorrectly creates ID

### ISSUE THREAD

**Issue by peterjcoffman** [xh/toolbox#344]
RecallsPanelModel creates the following ID spec:

```
    createId(data) {
        return data.brandName + data.recall_number;
    }
```
However, this is in error. The `brandName` property is added to the record by `RecallsPanelModel` during preprocessing: 

```
    processRecord(rawRec) {
        return {
            ...rawRec,
            brandName: rawRec.openfda.brand_name[0],
            genericName: rawRec.openfda.generic_name[0],
            recallDate: rawRec.recall_initiation_date,
            description: rawRec.product_description,
            recallingFirm: rawRec.recalling_firm,
            reason: rawRec.reason_for_recall
        };
    }
```

But `id` is derived from the raw record, not from the preprocessed data.

```
        // Note idSpec run against raw data here.
        const id = this.idSpec(raw),
            rec = this.getById(id);
```

Therefore, the `brandName` property is not available to `idSpec`, and we get malformed IDs. This usually works as expected since our ID also includes `recall_number`, but `recall_number` is occasionally undefined and we get this:

<img width="844" alt="image" src="https://user-images.githubusercontent.com/48924151/73695412-0cb72280-46a8-11ea-87c8-bd15b7d04f07.png">

**Comment by peterjcoffman** [comment]
PR: https://github.com/xh/toolbox/pull/345

**Comment by lbwexler** [comment]
Great Ticket and Fix -- @haynesjm42 and @amcclain  - I guess somebody was using an idSpec based on processed Data - us!
