### ISSUE TITLE
Error on launching 'Examples -> Portfolio' app

### ISSUE THREAD

**Issue by mpeckerman** [xh/toolbox#374]
1. Navigate to EX Toolbox -> Examples tab -> Portfolio tile
2. Click 'Launch app' button / icon
3. Error! 'this.init is not a function'

![Screen Shot 2020-03-03 at 3 41 48 PM (3)](https://user-images.githubusercontent.com/40367298/75817754-b7813600-5d65-11ea-9ef8-83447ecac1dc.png)

Error details:
    "stackTrace": {
        "0": "TypeError: this.init is not a function",
        "1": "    at Object.f [as Color] (https://toolbox-dev.xh.io/vendors~admin~app~portfolio/vendors~admin~app~portfolio.ea6c437f.js:1:302620)",
        "2": "    at LineChartModel.initializer (https://toolbox-dev.xh.io/portfolio/portfolio.ed56c376.js:1:42577)",
        "3": "    at _initializerDefineProperty (https://toolbox-dev.xh.io/portfolio/portfolio.ed56c376.js:1:40077)",
        "4": "    at new LineChartModel (https://toolbox-dev.xh.io/portfolio/portfolio.ed56c376.js:1:40994)",
        "5": "    at ChartsPanelModel.initializer (https://toolbox-dev.xh.io/portfolio/portfolio.ed56c376.js:1:32706)",
        "6": "    at _initializerDefineProperty (https://toolbox-dev.xh.io/portfolio/portfolio.ed56c376.js:1:30911)",
        "7": "    at new ChartsPanelModel (https://toolbox-dev.xh.io/portfolio/portfolio.ed56c376.js:1:31832)",
        "8": "    at DetailPanelModel.initializer (https://toolbox-dev.xh.io/portfolio/portfolio.ed56c376.js:1:38310)",
        "9": "    at _initializerDefineProperty (https://toolbox-dev.xh.io/portfolio/portfolio.ed56c376.js:1:35826)",
        "10": "    at new DetailPanelModel (https://toolbox-dev.xh.io/portfolio/portfolio.ed56c376.js:1:36821)"

**Comment by lbwexler** [comment]
This looks like an issue with the deployed app only.  So presumably a minimization issue.

**Comment by cnrudd** [comment]
Happens also on this basic charts demo page: https://toolbox-dev.xh.io/app/charts/line  but not on the other chart demo pages.

**Comment by cnrudd** [comment]
I'm also finding bug in my localhost instance: http://localhost:3000/app/charts/line

**Comment by cnrudd** [comment]
Bug is already reported in Highcharts repo:
https://github.com/highcharts/highcharts/issues/13083

**Comment by cnrudd** [comment]
This issue was fixed by locking Highcharts in Hoist-React to v8.0.0.
A tracking issue was created in Hoist-React to remind us to move Highcharts to the next corrected version when possible: https://github.com/xh/hoist-react/issues/1750

**Comment by cnrudd** [comment]
This is going to cause a bug for any of our client apps that use 
hoist-react v29+ and `Highcharts.Color(..)`

They can be fixed by making the same change as was made in this commit:
https://github.com/xh/toolbox/commit/5dac03224a9dfee6aaac74e82652f42fecfa4773
