### ISSUE TITLE
Missing Examples/Usages 

### ISSUE THREAD

**Issue by lbwexler** [xh/toolbox#399]
Catch all tickets for minor API usages that we don't capture with examples in toolbox.  Feel free to grab one, implement it, and cross if off

- [x] FilterChooser
- [ ] Persistence
- [x] FormField.requiredIndicator
- [x] Toolbar.enableOverflowMenu 
- [x] ColAutosizeButton
- [ ] autoAbortKey

**Comment by ghsolomon** [comment]
Looked like FilterChooser, FormField.requiredIndicator and Toolbar.enableOverflowMenu were already featured on Toolbox, so crossed those off.  Persistence is also demonstrated, but is there a particular example you had in mind?

**Comment by lbwexler** [comment]
I am happy to close this ticket.  At this point its obviously not a comprehensive or prioritized list in any way.  If we undertake a new project to really enhance our docs, don't think we would start with this.

Thanks for grabbing the low hanging fruit of that button
