### ISSUE TITLE
auth0 breaks `startOnDevice`

### ISSUE THREAD

**Issue by lbwexler** [xh/toolbox#447]
See stackTrace below.  Logging in using form did not help

{
    "stackTrace": {
        "0": "Error: ",
        "1": "      auth0-spa-js must run on a secure origin. See https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-do-i-get-auth0-spa-js-must-run-on-a-secure-origin for more information.",
        "2": "    ",
        "3": "    at eval (webpack-internal:///./node_modules/@auth0/auth0-spa-js/dist/auth0-spa-js.production.esm.js:17:91457)",
        "4": "    at new t (webpack-internal:///./node_modules/@auth0/auth0-spa-js/dist/auth0-spa-js.production.esm.js:17:91663)",
        "5": "    at eval (webpack-internal:///./node_modules/@auth0/auth0-spa-js/dist/auth0-spa-js.production.esm.js:17:103432)",
        "6": "    at eval (webpack-internal:///./node_modules/@auth0/auth0-spa-js/dist/auth0-spa-js.production.esm.js:17:2063)",
        "7": "    at Object.eval [as next] (webpack-internal:///./node_modules/@auth0/auth0-spa-js/dist/auth0-spa-js.production.esm.js:17:2168)",
        "8": "    at eval (webpack-internal:///./node_modules/@auth0/auth0-spa-js/dist/auth0-spa-js.production.esm.js:17:1105)",
        "9": "    at new Promise ()",
        "10": "    at r (webpack-internal:///./node_modules/@auth0/auth0-spa-js/dist/auth0-spa-js.production.esm.js:17:879)",
        "11": "    at Co (webpack-internal:///./node_modules/@auth0/auth0-spa-js/dist/auth0-spa-js.production.esm.js:17:103331)",
        "12": "    at OauthService.initAsync (webpack-internal:///./src/core/svc/OauthService.js:47:105)"
    }
}

**Comment by amcclain** [comment]
I think we would need to setup webpack dev server to run over HTTPS with a certificate (presumably self-signed)

https://v4.webpack.js.org/configuration/dev-server/#devserverhttps
