### ISSUE TITLE
Error in toolbox RestGrid example

### ISSUE THREAD

**Issue by lbwexler** [xh/toolbox#448]
Exception thrown:

LocalDate.get() requires a string of the form "YYYYMMDD"

**Comment by petradish** [comment]
In both `toolbox` and `toolbox_dev` DBs, I deleted the existing rows in the `Company` table and altered the `earnings_date' column to be of type varchar(10) so that the data is of type "YYYYMMDD" - Toolbox Dev is working well, but Prod is still throwing the exception. It's unclear to me why...

**Comment by lbwexler** [comment]
We looked together and its fixed now -- think it probably related to hibernate cache!

**Comment by lbwexler** [comment]
👍
