### ISSUE TITLE
Mysterious empty space at bottom of fullscreen mobile app

### ISSUE THREAD

**Issue by TomTirapani** [xh/toolbox#495]
Toolbox shows a mysterious empty space at the bottom of the page when in fullscreen mode. It's the background color of the `<body>`, implying that the height of `xh-viewport` has somehow been reduced.

It seems to trigger when completing the 0auth flow. Unclear at this point if this is a problem in client apps that don't implement that flow. It disappears upon suspending & reopening the shortcut, or rotating the device.

![IMG_1555](https://user-images.githubusercontent.com/3017757/115736124-f23b9880-a382-11eb-8a5f-81bd1a50567d.PNG)

**Comment by TomTirapani** [comment]
Yes, this seems to be specific to Toolbox and Auth0 - it hasn't been seen in the wild with client apps.

**Comment by amcclain** [comment]
Thanks for figuring this out - very happy you were able to find a workaround, and didn't see any issues with it looking on my device. Merged - happy to have that resolved.
