### ISSUE TITLE
Test Highcharts update to 9.3.x

### ISSUE THREAD

**Issue by amcclain** [xh/toolbox#522]
Noticed a new minor version available for Highcharts, with the major improvement being to tree shaking:

https://www.highcharts.com/blog/changelog/#highcharts
https://github.com/highcharts/highcharts/issues/8667

Would be great to test in Toolbox and ensure no unexpected breaking changes, but would also be very interested to run our `buildAndAnalyze` script before/after the update to see if we get any benefits in terms of bundle size. Whenever you have a chance, please let us know what you find!

**Comment by dsilberger** [comment]
The buildAndAnalyze script showed an extremely small difference in bundle size, on the order of about 13 kb. Performance qualitatively felt similar, and this was borne out by Lighthouse testing. Using the charts tab over multiple loads, Lighthouse rated toolbox similarly using both versions on all performance criteria. There was greater variability on each metric across loads on each version (9.3 vs. 9.1.2) than between the range of results for the two versions.

There don't appear to be any breaking changes, except to the extent we're interfacing with Google Sheets, which requires some new configuration and a new API key, but that is more of a Google change than a Highcharts change.

Overall, doesn't seem to be much reason to make the upgrade at this time.

**Comment by amcclain** [comment]
Thanks, Dan - scanning over that issue on the HC github, it remains unclear (to me) exactly how to take advantage of the tree shaking support / compatibility in this newer version, but that's OK - it's really not a priority for us at the moment.

I am glad you tested generally with the new version - we like to keep our deps updated even if they don't have any changes we know we want to put to immediate use. It's been much easier to do slow-but-steady updates, vs letting something fall way behind and then having a much bigger hurdle to upgrade across a few versions if/when we really _do_ need a new feature or fix.

Could you also test (if you have not already) the features available via the context menu on a chart - export, copy to clipboard, fullscreen view?  Those seem a bit more obscure and would be easy to miss a breaking change (I know there shouldn't be any with a minor version bump, but better safe than sorry.)

If that all looks good, please go ahead and update the version of HC used here in Toolbox to the latest. If it's truly just the package.json / yarn.lock file that changed, you can push that to `develop` directly. If any other changes pls commit to a branch and open a pull request.

Thanks!

**Comment by dsilberger** [comment]
All the context menu operations worked. Pushed the minor version update directly to `develop`.
