### ISSUE TITLE
Portfolio example grid model requires manual refresh to enable websockets

### ISSUE THREAD

**Issue by PeteDarinzo** [xh/toolbox#627]
The portfolio example app's grid model relies on WebSockets to update P&L data. 

Upon loading the app, the P&L values will remain static until the grid is manually refreshed, then they will start to update via WebSocket approximately once every five seconds.

The intended behavior is for the grid to be updated through WebSocket messages immediately after loading, a manual refresh should not be required.

**Comment by lbwexler** [comment]
Not a critical priority, but given that this is our premier example, and our only example of websockets, it really ought to work properly.  Happy to take a look with you -- let me know.
