### ISSUE TITLE
Admin Grid performance test page should include n-level nesting

### ISSUE THREAD

**Issue by amcclain** [xh/toolbox#687]
As we saw with recent bug https://github.com/xh/hoist-react/issues/3550, it is important to test multiple levels of nesting with tree grid use cases.  We should enhance https://toolbox-dev.xh.io/admin/tests/grid to nest generated records more than a single level deep.

**Comment by jskupsik** [comment]
I have added deeper tree nesting as well as option to use numeric ids - without the fix, it is now possible to reproduce the bug.
